version: "3.7"

services:

  nginx:
    image: nginx:1.17.2-alpine
    ports: 
      - "8080:8080"
    networks:
      - backend
    volumes:
      - "./conf/nginx-default.conf:/etc/nginx/conf.d/default.conf"

  tomcat:
    image: tomcat:9
    networks:
      - backend
    volumes:
      - "./conf/manager-context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml"
      - "./conf/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"

  postgres:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  adminer:
    image: adminer:4.7
    networks:
      - backend
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./conf/adminer-login-servers.php:/var/www/html/plugins-enabled/login-servers.php"

networks:
  backend:

volumes:
  db-data:
